"""Added default value to icon in work_experience

Revision ID: 46c40cbb9eef
Revises: 3dc5a96f21f8
Create Date: 2025-02-01 01:23:51.624499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '46c40cbb9eef'
down_revision = '3dc5a96f21f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.drop_column('achievements')

    # ### end Alembic commands ###
