"""Added default value to icon in work_experience

Revision ID: 795c499f51c2
Revises: 46c40cbb9eef
Create Date: 2025-02-01 01:28:31.560203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '795c499f51c2'
down_revision = '46c40cbb9eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###
